import type { Database } from 'bun:sqlite';
import { readFileSync, writeFileSync, renameSync, unlinkSync } from 'fs';
import { join } from 'path';
import { getProfileByProject } from '../sqlite/developer-profile.js';
import { getReflectionsByProject } from '../sqlite/reflections.js';
import { getRecentObservations } from '../sqlite/observations.js';
import { getConfig } from '../../shared/config.js';
import { logger } from '../../utils/logger.js';

const SMRITI_START_TAG = '<!-- smriti-context:start -->';
const SMRITI_END_TAG = '<!-- smriti-context:end -->';

export function generateClaudeMdSection(db: Database, project: string): string {
  const config = getConfig();
  const maxEntries = config.get('claudemd', 'maxEntries');

  const profile = getProfileByProject(db, project, { limit: maxEntries });
  const reflections = getReflectionsByProject(db, project, { limit: 5 });
  const patterns = getRecentObservations(db, project, { limit: 20 })
    .filter(o => o.importance >= 7 && ['pattern', 'decision', 'bugfix'].includes(o.type));

  const sections: string[] = [];
  sections.push(SMRITI_START_TAG);
  sections.push('## Project Memory (auto-generated by Smriti)\n');

  if (profile.length > 0) {
    sections.push('### Developer Profile\n');
    for (const entry of profile.slice(0, maxEntries)) {
      sections.push(`- **[${entry.category}]** ${entry.description}`);
    }
    sections.push('');
  }

  if (reflections.length > 0) {
    sections.push('### Key Insights\n');
    for (const r of reflections) {
      sections.push(`- ${r.insight}${r.category ? ` _(${r.category})_` : ''}`);
    }
    sections.push('');
  }

  if (patterns.length > 0) {
    sections.push('### Important Patterns & Decisions\n');
    for (const p of patterns.slice(0, maxEntries)) {
      const facts: string[] = p.facts ? JSON.parse(p.facts) : [];
      sections.push(`- **[${p.type}]** ${p.title}${facts[0] ? ': ' + facts[0] : ''}`);
    }
    sections.push('');
  }

  sections.push(SMRITI_END_TAG);
  return sections.join('\n');
}

export function updateClaudeMd(projectDir: string, newSection: string): void {
  const filePath = join(projectDir, 'CLAUDE.md');
  let content = '';

  try {
    content = readFileSync(filePath, 'utf-8');
  } catch {
    // File doesn't exist — will create
  }

  const startIdx = content.indexOf(SMRITI_START_TAG);
  const endIdx = content.indexOf(SMRITI_END_TAG);

  if (startIdx !== -1 && endIdx !== -1) {
    // Replace existing Smriti section
    content = content.slice(0, startIdx) + newSection + content.slice(endIdx + SMRITI_END_TAG.length);
  } else if (content.trim()) {
    // Append to existing file
    content = content.trimEnd() + '\n\n' + newSection + '\n';
  } else {
    // New file
    content = newSection + '\n';
  }

  // Atomic write: write to temp file, then rename
  const tmpPath = filePath + '.smriti-tmp';
  try {
    writeFileSync(tmpPath, content, 'utf-8');
    renameSync(tmpPath, filePath);
    logger.info('CLAUDEMD', 'Updated CLAUDE.md', { projectDir });
  } catch (error) {
    logger.warn('CLAUDEMD', 'Failed to write CLAUDE.md', { error: (error as Error).message });
    // Clean up temp file
    try { unlinkSync(tmpPath); } catch {}
  }
}
